name: circle_calculator
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Abdalla-Medhat/circle_calculator.git

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

executables:
  circleC: my_project
  
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
